version: '2'

volumes:
  peer1.org2.test2.com:

networks:
  test2:
    external:
      name: root_test2

services:

  peer1.org2.test2.com:
    container_name: peer1.org2.test2.com
    image: hyperledger/fabric-peer:2.2.0
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=root_test2
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.org2.test2.com
      - CORE_PEER_ADDRESS=peer1.org2.test2.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.test2.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.test2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - $CRYPTO_BASE/organizations/peerOrganizations/org2.test2.com/peers/peer1.org2.test2.com/msp:/etc/hyperledger/fabric/msp
        - $CRYPTO_BASE/organizations/peerOrganizations/org2.test2.com/peers/peer1.org2.test2.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.test2.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - test2
