version: '2'

networks:
  test:
    external:
      name: root_test

services:

  ca.org4.test.com:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_CSR_HOSTS=localhost, ca.org4.test.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - $CRYPTO_BASE/organizations/fabric-ca/org4:/etc/hyperledger/fabric-ca-server
    container_name: ca.org4.test.com
    networks:
      - test
